### ISSUE TITLE
LimitCharacters not stripping out <p> tag on translation

### ISSUE THREAD

**Issue by muskie9** [bummzack/translatable-dataobject#22]
I'm not sure if this bug is in `StringField` or if it's related to this module or the Translatable module. I have a DataObject with an `HTMLText` db field that is translatable. When I `<% loop Master.MyDataObjects %>` it is getting the correct translation set, but my `$T(DBFieldName).LimitCharacters(50)` within the loop doesn't strip the `<p>`.

I'm trying to track down where exactly the issue is but was wondering if you knew of anything similar or a workaround.

**Comment by bummzack** [comment]
Fixed this. Sorry I kept you waiting for an answer for so long.

**Comment by muskie9** [comment]
No worries, thanks for the update!
