### ISSUE TITLE
Fatal error on the CMSMainTest

### ISSUE THREAD

**Issue by ennitje** [bummzack/translatable-dataobject#23]
After setting up a translatable DataObject the CMSMainTest will produce an fatal error. The error is triggered by Translatable::get_existing_content_languages() (TranslatableDataObject - line 524)

`Fatal error: Couldn't run query: SELECT Distinct "Locale" FROM "SiteTree" GROUP BY "Locale" Table 'ss_tmpdb4971656.SiteTree' doesn't exist in /var/www/project_name/framework/model/MySQLDatabase.php on line 598`

Using a clean 3.1.12 installation of silverstripe + 2.0.6 translatable addon.

**Comment by bummzack** [comment]
Are you sure you reported this at the right place? Seems to be related to the "translatable" Module and not "translatable-dataobject". Does it work without using "translatable-dataobject"?

**Comment by ennitje** [comment]
Without using the "translatable-dataobject" the test is running fine.

**Comment by bummzack** [comment]
I have no idea what triggers that error. The error-code isn't really helpful either.

I assumed the culprit would be `TranslatableUtility::get_content_languages`, since it fires a query like the one that is causing the issue... but replacing said function with just a `return array()` doesn't change anything.

**Comment by ennitje** [comment]
It looks like that every FunctionalTest will produce the error.

**Comment by ennitje** [comment]
I looked a bit into it. If you add the TranslatableDataObject extension like `Testimonial::add_extension("TranslatableDataObject('Title','Content')")` the functional tests get through  the `TranslatableDataObject::get_extra_config()` method which calls `TranslatableDataObject::collectDBFields()` ->`TranslatableDataObject::get_target_locales()`. The `TranslatableDataObject::get_target_locales()` is calling `Translatable::get_existing_content_languages()` where the query `$query = new SQLQuery("Distinct \"Locale\"","\"$baseTable\"",$where, '', "\"Locale\"");'` is fired. In the default temporary test table there is no field Locale / Translatable. So you can add
```php
protected $requiredExtensions = array(
	'SiteTree' => array('Translatable')
);
```
to a functional test and the error is gone. 

My temporary solution is to modify the TranslatableDataObject::get_extra_config():
```php
public static function get_extra_config($class, $extension, $args) {
		if($args){
			self::$arguments[$class] = $args;
		}
		if(!SapphireTest::is_running_test()){
			return array (
				'db' => self::collectDBFields($class)
			);
		}
	}
```

**Comment by bummzack** [comment]
Thanks for figuring out the source of the problem and for providing a workaround. I'm tempted to add your solution to my codebase, but that would then make custom tests that use the TranslatableDataObject unusable...

**Comment by ennitje** [comment]
That's right, so what about modifying the `TranslatableDataObject::get_target_locales()` method  like:
```php
protected static function get_target_locales(){
		// if locales are explicitly set, use these
		if(is_array(self::$locales)){
			return self::$locales;
			// otherwise check the allowed locales. If these have been set, use these
		} else if(Translatable::get_allowed_locales() !== null){
			return Translatable::get_allowed_locales();
		} else {
			if(SapphireTest::is_running_test()){
			//return locales for testing
			return array();
			}else{
			// last resort is to take the existing content languages
			return array_keys(Translatable::get_existing_content_languages());
			}
		}
	}
```
So, when you are writing custom tests for the TranslatableDataObject you just have to setup the array with the locales defined in your testing yml or php.
