### ISSUE TITLE
How to pull translation strings in when importing dataObject via CSV

### ISSUE THREAD

**Issue by mikep165** [bummzack/translatable-dataobject#29]
I am about to do some large CSV data imports to populate postal codes and related data for some new DataObjects I've built.  The translatable fields are in place and working great, but I don't know how to reference them when I pull new data in.  I am building a custom controller to do the import (https://docs.silverstripe.org/en/3.1/developer_guides/integration/csv_import/). Any advice would be greatly appreciated.

Mike

**Comment by bummzack** [comment]
By default, the field names are composed of *Fieldname* and *Locale*, joined by two underscores. So if you have a Field named "Title" and 3 locales (en_US, fr_FR, de_DE) where EN is the default, you will get the following fields:
```
Title // for english
Title__fr_FR // for french
Title__de_DE // for german
```
You should be able to set these directly during import, eg. `MyDataObject->Title__fr_FR = 'Somevalue'`.

When in doubt, look at your DB table schema.

**Comment by mikep165** [comment]
that worked nicely, thanks!
