### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by wernerkrauss** [bummzack/translatable-dataobject#33]
When installing a project on SS 3.2 with both composer packages translatable and translatable-dataobject i get a nasty error on the first install which breaks dev/build:

[User Warning] Translatable module is not installed but required.

removing translatable-dataobject for first install and installing after database was setup once fixes this issue, but is totally annoying

**Comment by wernerkrauss** [comment]
Commenting out the clause at https://github.com/bummzack/translatable-dataobject/blob/master/code/extensions/TranslatableDataObject.php#L72 helps. 

I wonder if this is really needed, cause above it's checked if SiteTree class exists. And you could also require CMS module in composer.json.

**Comment by bummzack** [comment]
I honestly can't recall why this check is in there. I'd be fine with removing it if you think that improves the situation.

**Comment by wernerkrauss** [comment]
it absolutely would, imho the above two checks are enough and if SiteTree class exists there must be a db table for it. 

Please release another minor version without this check!

**Comment by bummzack** [comment]
Done.

**Comment by wernerkrauss** [comment]
Thanks a lot! Works like a charm now.

**Comment by gavro** [comment]
@bummzack @wernerkrauss Perhaps I found the reason why this check was present. Using SS3.4, clean install. Trying with an empty DB, dev/build, I'm getting the following DB error:
```
Fatal error: Uncaught exception 'SS_DatabaseException' with message 'Couldn't run query:
SELECT Distinct "Locale"
FROM "SiteTree"
GROUP BY "Locale"
```

This is triggered from ```TranslatableDataobject::get_extra_config()``` --> ```self::collectDBFields($class)``` --> ```self::get_target_locales()``` --> ```Translatable::get_existing_content_languages()```

I can't build the site unless I remove any configured TranslatableDataObjects.
