### ISSUE TITLE
removing fields from translatabletabset

### ISSUE THREAD

**Issue by guyvanbael** [bummzack/translatable-dataobject#42]
I'm trying to hide a field from each language tab.
Tabs are created using $fields->add($this->getTranslatableTabSet());

then i wrote this piece of code, but no fields gets removed from the language tabs
    $locales = Translatable::get_allowed_locales();
    foreach($locales as $locale) {
      $locale = i18n::get_lang_from_locale($locale);
      $langName = i18n::get_language_name($locale,true);
      $fields->removeFieldFromTab('Root.'.$langName,'Titel');
    }

Anyone?

**Comment by bummzack** [comment]
You'll have to use the proper field-name to remove the field.
Eg. to remove "Title" in "en_US", you'll need something like:

    $fields->removeByName(TranslatableDataObject::localized_field('Title', 'en_US'));

The `localized_field` method should create the proper field identifier for the given name and locale.

**Comment by guyvanbael** [comment]
That works like a charm! Thanx a million. 
I owe you a beer :-)
